---
- name: Update apt packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: full
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Check if reboot required on Ubuntu
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Reboot if required on Ubuntu
  ansible.builtin.reboot:
    msg: Rebooting due to a kernel update
  when: (ansible_distribution in ["Ubuntu", "Debian"]) and reboot_required_file.stat.exists

- name: Install packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present

#- name: Install pip packages
#  ansible.builtin.pip:
#    name: "{{ pip_packages }}"
#    state: present

#- name: Create Docker directory
#  ansible.builtin.file:
#    path: "{{ docker_dir }}"
#    state: directory
#    owner: "{{ username }}"
#    group: "{{ username }}"
#    mode: "0755"